# Generated by Django 2.2 on 2020-08-04 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolemoduleaction',
            name='module_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_module_actions', related_query_name='role_module_action', to='permission.ModuleAction'),
        ),
        migrations.AddField(
            model_name='rolemoduleaction',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Role'),
        ),
        migrations.AddField(
            model_name='moduleaction',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_actions', related_query_name='module_action', to='permission.Module'),
        ),
        migrations.AddField(
            model_name='moduleaction',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='module',
            name='app_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.AppSource', verbose_name='App Source'),
        ),
        migrations.AddField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.Module'),
        ),
    ]
