# Generated by Django 2.2 on 2020-08-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for soft delete.', verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('source_key', models.CharField(max_length=55)),
                ('salt_key', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'App Source',
                'verbose_name_plural': 'App Source',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for soft delete.', verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='Use is flag to distinguish between system role and user defined role', verbose_name='Is System Role')),
                ('app_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.AppSource', verbose_name='App Source')),
                ('default_module_action', models.ForeignKey(blank=True, help_text='This module action will be used as landing page when this role log-in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_roles', related_query_name='default_roles', to='permission.ModuleAction', verbose_name='Default Module Action')),
                ('module_actions', models.ManyToManyField(blank=True, help_text='To map role with BE permission in case needed', related_name='roles', related_query_name='role', through='permission.RoleModuleAction', to='permission.ModuleAction', verbose_name='module_actions')),
                ('permissions', models.ManyToManyField(blank=True, help_text='To map role with BE permission in case needed', to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
