# Generated by Django 2.2 on 2020-08-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for soft delete.', verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Lookup Type Name')),
                ('key', models.CharField(max_length=50, verbose_name='Lookup Type key')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup_management.LookupType')),
            ],
            options={
                'db_table': 'lookup_type',
            },
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for soft delete.', verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Lookup name')),
                ('key', models.CharField(max_length=50, verbose_name='Lookup key')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Lookup order')),
                ('info_1', models.CharField(blank=True, max_length=255, null=True)),
                ('info_2', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lookup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', related_query_name='lookup', to='lookup_management.LookupType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup_management.Lookup')),
            ],
            options={
                'db_table': 'lookup',
            },
        ),
    ]
