# Generated by Django 4.0.5 on 2024-08-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup_management.lookup', verbose_name='Parent Lookup'),
        ),
    ]
