# Generated by Django 4.0.5 on 2024-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_requestresponselogdata_delete_requestresponselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponselogdata',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
